version: "3"

services:
  mysql:
    image: mysql:5.7.21
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: instagram

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      cluster.blocks.read_only_allow_delete: "false"
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - index.blocks.read_only_allow_delete=null
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  api-instagram:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - mysql
      - elasticsearch
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/instagram
      FE_AZURE_TRANSLATOR_KEY: '2084ddd8ecf545afb49c15c6287bc7a0'
      FE_AZURE_SERVICE_NAMESPACE: 'hashtags'
      FE_AZURE_SHARED_ACCESS_POSTS_KEY_NAME: ''
      FE_AZURE_SHARED_ACCESS_POSTS_KEY_VALUE: ''
      FE_AZURE_SHARED_ACCESS_HASHTAGS_KEY_NAME: ''
      FE_AZURE_SHARED_ACCESS_HASHTAGS_KEY_VALUE: ''
      FE_ELASTICSEARCH_HOST: 'elasticsearch'
    stdin_open: true
    tty: true

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.1
    container_name: kibana
    ports:
      - 5601:5601

volumes:
  mysql-data:
  elasticsearch-data:
