version: "3"

services:
  mysql:
    image: mysql:5.7.21
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: instagram

  api-instagram:
    build: .
    ports:
      - "9000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - mysql
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/instagram
    stdin_open: true
    tty: true

volumes:
  mysql-data:
