# Generated by Django 2.1.3 on 2018-11-28 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20181127_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shortcode', models.CharField(max_length=100, unique=True)),
                ('tags', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
