# Generated by Django 2.1.3 on 2018-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='languages',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
