# Generated by Django 2.1.3 on 2018-11-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_tag_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_count',
            field=models.IntegerField(null=True),
        ),
    ]
