# Generated by Django 2.1.3 on 2018-11-30 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_tag_last_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPriority',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
