# Generated by Django 2.1.3 on 2018-12-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_tagpriority'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='injest_at',
            field=models.DateTimeField(null=True),
        ),
    ]
