# Generated by Django 2.1.3 on 2018-12-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_textsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='injest_at',
            new_name='ingest_at',
        ),
    ]
