# Generated by Django 2.1.3 on 2018-12-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_auto_20181207_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='identifier',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
