# Generated by Django 2.1.3 on 2018-12-08 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0010_auto_20181207_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='display_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='taken_at_timestamp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='shortcode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
    ]
