# Generated by Django 2.1.3 on 2018-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_auto_20181208_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='display_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
