# Generated by Django 2.1.3 on 2018-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_auto_20181208_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
