# Generated by Django 2.1.3 on 2018-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_auto_20181208_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identifier',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
