# Generated by Django 2.1.3 on 2018-12-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_auto_20181210_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsearch',
            name='status',
            field=models.CharField(choices=[('C', 'Criado'), ('P', 'Processando'), ('O', 'Processado')], default='C', max_length=1),
        ),
    ]
