apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: issuer-letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "fer.esp@gmail.com"
    privateKeySecretRef:
      name: issuer-letsencrypt
    http01: {}
