apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api-instagram.dev.fernandoe.com
      http:
        paths:
          - backend:
              serviceName: api-instagram
              servicePort: 80
  tls:
    - hosts:
        - api-instagram.dev.fernandoe.com
      secretName: api-instagram-dev-fernandoe-com-tls
